[build]
  # build INSIDE the subfolder that has package.json
  base = "ecom-product-app"
  # use npm install so it can reconcile the lockfile mismatch
  command = "npm install --no-audit --no-fund && npm run build"
  # because base is set, publish should be just "build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
