[build]
  base = "ecom-product-app"
  command = "npm ci && npm run build"
  publish = "ecom-product-app/build"

# SPA routing (React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
